- alias: Turn_on_Flo
  trigger:
    platform: state
    entity_id: sensor.0x0017880108005bb6_action
    to: 'on'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: Flo
      scene_name: Entspannen

- alias: Turn_off_Flo
  trigger:
    platform: state
    entity_id: sensor.0x0017880108005bb6_action
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.flo_fado
# Autmoation should call HUE API at this path: http://192.168.178.21/api/!secret huetoken/groups/7/action
# Body: { "on": false }