- alias: Turn_on_Flo
  trigger:
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'on'
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'off'
  condition:
    - condition: state
      entity_id: 'light.flo_fado'
      state: 'off'
  action:
    - service: rest_command.flo_lightOn_request
    - service: timer.start
      entity_id: timer.flo_debounce

- alias: Turn_off_Flo
  trigger:
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'on'
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'light.flo_fado'
        state: 'on'
      - condition: state
        entity_id: timer.flo_debounce
        state: idle
  action:
    service: rest_command.flo_lightOff_request

- alias: Switch_Flo
  trigger:
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'on'
    - platform: state
      entity_id: sensor.0x0017880108005bb6_action
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'light.flo_fado'
        state: 'on'
      - condition: state
        entity_id: timer.flo_debounce
        state: active
  action:
    - service: input_select.select_next
      entity_id: input_select.scene_flo
    - service: hue.hue_activate_scene
      data:
        group_name: "Flo"
        scene_name: {{ input_select.scene_flo }}
    - service: timer.start
      entity_id: timer.flo_debounce

# Template for using data_tamplate {{ trigger.from_state.state }}
# data_template: 
#         group_name: "Flo" #TODO: change to "Gang" after creating in HUE App
#         scene_name: >
#           {% if is_state('input_select.scene_flo', 'on') or (is_state('input_boolean.flo_nachtmodus', 'on') and is_state('input_boolean.simon_nachtmodus', 'on')) %} 
#             Nacht 2
#           {% else %} 
#             Hell
#           {% endif %}


# - alias: Turn_off_Flo
#   trigger:
#     platform: state
#     entity_id: sensor.0x0017880108005bb6_action
#     to: 'off'
#   action:
#     service: rest_command.flo_lightOff_request
# Autmoation should call HUE API at this path: http://192.168.178.21/api/!secret huetoken/groups/7/action
# Body: { "on": false }