
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#Custom switch for nighmode
input_boolean:
  christian_nachtmodus:
    name: Nachtmodus von Christian
    initial: off
    icon: mdi:weather-night
  simon_nachtmodus:
    name: Nachtmodus von Simon
    initial: off
    icon: mdi:weather-night
  flo_nachtmodus:
    name: Nachtmodus von Florian
    initial: off
    icon: mdi:weather-night

#wake_on_lan:

samsungtv:
  - host: 192.168.178.40
    #turn_on_action:
    #  - service: wake_on_lan.send_magic_packet
    #    data:
    #      mac: !secret samsungTvMac

device_tracker:
#Device tracker using FritzBox -> hopefully better then the GPS thing
  - platform: fritz
    host: 192.168.178.1
    password: !secret fritz_password
    interval_seconds: 5
    consider_home: 60
    track_new_devices: yes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
