
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


device_tracker:
  - platform: fritz
    host: 192.168.178.1
    password: !secret fritz_password
    interval_seconds: 5
    consider_home: 60
    track_new_devices: yes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
