
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#Custom switch for nighmode
# When nightmode is turned on -> set scene select to "Nachtlicht"
input_boolean:
  christian_nachtmodus:
    name: Nachtmodus von Christian
    initial: off
    icon: mdi:weather-night
  simon_nachtmodus:
    name: Nachtmodus von Simon
    initial: off
    icon: mdi:weather-night
  flo_nachtmodus:
    name: Nachtmodus von Florian
    initial: off
    icon: mdi:weather-night
  test_mode:
    name: test modus
    initial: off
    icon: mdi:weather-night
  wifi_down:
    name: WLAN Störung
    initial: off
    icon: mdi:wifi-strength-alert-outline

#selector for scene in Flo´s room
input_select:
  scene_flo:
    name: Scene Flo
    options:
      - Hell
      - Sonnenuntergang Savanne
      - Tropendämmerung
      - Nordlichter
      - Frühlingsblüten
      - Nachtlicht
    initial: Hell
  scene_chris:
    name: Scene Chris
    options:
      - Standard
      - Sonnenuntergang Savanne
      - Frühlingsblüten
      - Goldener Teich
      - Fernsehen
      - Weglicht
    initial: Standard
    

#wake_on_lan:
samsungtv:
  - host: 192.168.178.40
    port: 8001
    #turn_on_action:
    #  - service: wake_on_lan.send_magic_packet
    #    data:
    #      mac: !secret samsungTvMac

#setup for zigbee2mqtt
mqtt:
  discovery: true
  #broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

device_tracker:
#Device tracker using FritzBox -> hopefully better then the GPS thing
  - platform: fritz
    host: 192.168.178.1
    password: !secret fritz_password
    interval_seconds: 5
    consider_home: 60
    track_new_devices: yes

#Timer to catch multible pressing of smart button
timer:
  flo_debounce:
    duration: '00:0:05'
  chris_debounce:
    duration: '00:0:07'
  garderobe_debounce_dim: #after 45 secounds the light should be dimmed in Garderobe
    duration: '00:01:00'
  garderobe_debounce: # after 1 minute the light should be turned off in Garderobe
    duration: '00:01:30'
  gang_debounce_dim: #after 45 secounds the light should be dimmed in Garderobe
    duration: '00:01:00'
  gang_debounce: # after 1 minute the light should be turned off in Garderobe
    duration: '00:01:30'

# Text to speech
tts:
  - platform: google_translate

#customize: !include customize.yaml
rest_command: !include rest_commands.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
