- platform: mqtt
  name: Ambilight Wohnzimmer
  state_topic: "ambilightLamp/light/status"
  command_topic: "ambilightLamp/light/switch"
  brightness_state_topic: "ambilightLamp/brightness/status"
  brightness_command_topic: "ambilightLamp/brightness/set"
  rgb_state_topic: "ambilightLamp/rgb/status"
  rgb_command_topic: "ambilightLamp/rgb/set"
  state_value_template: "{{ value_json.state }}"
  brightness_value_template: "{{ value_json.brightness }}"
  rgb_value_template: "{{ value_json.rgb | join(',') }}"
  effect_command_topic: "ambilightLamp/effect/set"
  effect_state_topic: "ambilightLamp/effect/status"
  effect_list : [slow, medium, fast]
  qos: 0
  #payload_on: "ON"
  #payload_off: "OFF"
  optimistic: true
  on_command_type: 'brightness'

- platform: mqtt
  name: Ambilight Test
  schema: json
  command_topic: "ambilightLamp/light/set"
  state_topic: "ambilightLamp/light/status"
  brightness: true
  rgb: true
  white_value: true
  optimistic: true